>gi|84043963|ref|NP_056988.3| eukaryotic translation initiation factor 5B [Homo sapiens]
YK---EDEIPV---LKDEL------IHE-LKQTLNAI--------------KLEEKGVYV
QASTLGSLEALLEFLKT---S----------EVPYAGINIGPVHKKDVMKASVML--E--
-H--DPQYAVILAFDVRIERDAQEMADSL--GVRIFSAEIIYHLFDAFTKYRQ------D
YKKQKQ--EEF
>gi|291224326|ref|XP_002732156.1| PREDICTED: hypothetical protein, partial [Saccoglossus kowalevskii]
VQ---QDEIEI---CKEEV------EAA-LEDTLKSF--------------KLSDRGVLV
QASTLGSLEALLEFLRT---S----------KIPYAGINIGPVHKRDIMKAMVML--E--
-H--DTQYAVLLAFDVKVEREAQEMAEKE--GVRIFQADIIYHLFDSFMRYRD------E
LKQKKR--EEF
>gi|260828382|ref|XP_002609142.1| hypothetical protein BRAFLDRAFT_131372 [Branchiostoma floridae]
YK---EDEVDI---CKEEV------ARI-LKQTLETI--------------RVQERGVYV
QASTLGSLEALLEFLKT---S----------KIPFAGINIGPVHKKDVMKASIML--E--
-HD--SQYAVILAFDVRVERDAQELADSL--GIRIFTADIIYHLFDSFMKYRD------D
MKKQKQ--EEL
>gi|328778392|ref|XP_392101.4| PREDICTED: eukaryotic translation initiation factor 5B [Apis mellifera]
EK---SDEVEV---LKEEI------AKE-LSSALGNI--------------RLAERGVYV
QASTLGALEALLDFLKS---S----------KIPYAGIRIGPVVKKDVMKASIML--E--
-H--DSQYATILAFDVKIERDAQELADSL--GVKIFQADIIYHLFDKFTAYRE------E
LKQRKR--DEN
>gi|350416628|ref|XP_003491025.1| PREDICTED: eukaryotic translation initiation factor 5B-like [Bombus impatiens]
HK---PDEVDV---LKEEI------AKE-LTSALGNI--------------RLVERGVYV
QASTLGALEALLDFLKS---S----------KIPYAGIRIGPVVKKDVMKASIML--E--
-H--DSQYATILAFDVKIERDAQELADSL--GVKIFQADIIYHLFDKFTSYRE------E
LKQRKR--DEN
>gi|321479239|gb|EFX90195.1| hypothetical protein DAPPUDRAFT_205517 [Daphnia pulex]
YH---PDEVEI---CKEEV------AHE-LKSALGRI--------------KLQDRGVYV
QASTLGSLEALLEFLKT---S----------EIPYANIRIGPVVKKDVMKASTML--E--
-H--NAQYAVILAFDVKIERDAQEMADSV--GVKIFQADIIYHLFDSFMKYRD------E
LKAKKR--EEF
>gi|405972338|gb|EKC37111.1| Eukaryotic translation initiation factor 5B [Crassostrea gigas]
KR---DDEVEY---YKEEL------STA-LKEVLSGI--------------KLTERGVFV
QASTLGSLEALLEFLRT---S----------KIPYAGINIGPVHKKDIMKASIML--E--
-H--DSQYAVILAFDVRVEREAQEMADSL--GVKIFTADIIYHLFDKFMAFRD------E
LKKKRQ--DEF
>gi|383849659|ref|XP_003700462.1| PREDICTED: eukaryotic translation initiation factor 5B-like [Megachile rotundata]
QK---PDEVEV---LKEEI------AKE-LSSALRNI--------------RLAERGVYV
QASTLGALEALLDFLKS---S----------KIPYAGIRIGPVVKKDVMKASIML--E--
-H--DSQYATILAFDVKIERDAQELADSL--GVKIFQADIIYHLFDKFTAYRE------E
LKQRKR--NEN
>gi|91080893|ref|XP_973325.1| PREDICTED: similar to AGAP004824-PA [Tribolium castaneum]
QK---SDEVEI---LREEV------SRE-LKSALSNI--------------KLQERGVYV
QASTLGSLEALLEFLRT---S----------KIPYSGIRIGPVVKKDVMKASIML--E--
-H--ESQYATILAFDVRVERDAQELADSL--GVKIFQADIIYHLFDKFMAYRE------E
LKQKKR--EEF
>gi|24656849|ref|NP_651974.1| eIF5B, isoform B [Drosophila melanogaster]
HK---PDEVEI---CTEEV------ARE-LKSALSHI--------------KLAQTGVHV
QASTLGSLEALLEFLRT---S----------KIPYSAIRIGPVVKRDVMKASTML--E--
-H--EAQYATILAFDVKIEREAQEMADSL--GVKIFQADIIYHLFDKFTAYRE------E
LKQKKR--EEF
>gi|118790039|ref|XP_317984.3| AGAP004824-PA [Anopheles gambiae str. PEST]
HK---PDEVEI---FREIV------ARD-LKSALNSI--------------KLSDRGVYV
QASTLGSLEALLEFLRT---S----------KIPYSGIRIGPVVKRDVMKASTML--E--
-H--ENQYATILAFDVKVERDAQDLADNL--GVKIFQADIIYHLFDKFMAYRE------E
IKQRKR--DEF
>gi|390334562|ref|XP_001199006.2| PREDICTED: eukaryotic translation initiation factor 5B-like isoform 1 [Strongylocentrotus purpuratus]
EQ---PDEIEI---YREEV------AHL-LKAALTSI--------------KMSERGVYV
QASTLGSLEALLEFLRT---S----------KIPYSGINIGPVHKKDVMKASVML--E--
-H--DGQYAVILAFDVKVERDAQEMADRE--GIKVFQADIIYHLFDRFMAYRE------E
LKKRNK--ELH
>gi|193627337|ref|XP_001949877.1| PREDICTED: eukaryotic translation initiation factor 5B-like [Acyrthosiphon pisum]
NK---ADEVER---LKEVV------AKE-LKSALSTI--------------KLQDRGVYV
QASTLGSLEALLDFLRS---S----------KIPYSNIRIGPVVKKDVMKASIML--E--
-H--SPIYATILAFDVKVERDAQELADTL--NVKIFQADIIYHLFDKFTAYQD------D
LKKKNR--DQF
>gi|241616761|ref|XP_002408016.1| translation initiation factor if-2, putative [Ixodes scapularis]
HH---PDEVEV---LKDEV------SRS-LKEVMSGF--------------KLSERGVYV
QASTLGSLEALLEFLRV---S----------KIPYSGIRIGPVVKKDVMKASIML--E--
-H--DTQYAVILAFDVKVERDAQELADSL--GVRIFQADIIYHLFDKFMAYRE------E
LRQKKR--DEF
>gi|242021080|ref|XP_002430974.1| eukaryotic translation initiation factor 5B, putative [Pediculus humanus corporis]
EK---PDEIPI---WCEEV------SKE-LKSALSSI--------------KLKERGVYV
QASTLGSLEALLEFLKT---S----------KIPYSGIKIGPVVKKDVMKASIML--E--
-H--ESQYATILAFDVKIERDAQELADSL--GVKIFQADIIYHLFDKFMAYRE------E
LKQKKR--DEF
>gi|345490275|ref|XP_003426342.1| PREDICTED: hypothetical protein LOC100122877 isoform 1 [Nasonia vitripennis]
QK---PDEVEI---LKEEI------AKE-LTHALGKI--------------KLAERGVFV
QASTLGALEALLDFLKS---S----------KIPYAGIRIGPVVKKDVMKASIML--E--
-H--DSQYATILAFDVKIERDAQELADSL--GVKIFQADIIYHLFDRFIEYKE------Q
LRQRKR--DEH
>gi|196015400|ref|XP_002117557.1| hypothetical protein TRIADDRAFT_61546 [Trichoplax adhaerens]
KK---PDEVDI---LKEEV------SAR-LAESLNSI--------------KLSDRGVYV
QASTLGSLEALIEFLKT---S----------KIPYSGINVGPVHKKDVMKASVML--E--
-H--DAQYAVILAFDVKIEQDATDMAKKL--GVRIFSADIIYHLFDKFMAFRE------E
AIKKLK--EQH
>gi|221121018|ref|XP_002155134.1| PREDICTED: similar to Eukaryotic translation initiation factor 5B [Hydra magnipapillata]
QS---LDEVDV---LKEDV------DNF-VSSSLKAI--------------NVSERGVYV
QASTLGSLEALLEFLKT---S----------KIPYCGVNIGPVHKKDIMRCSVML--E--
-H--EPMYAVILAFDVKIEKDVQEFADRE--GVRIFSAEIIYHLFDQFTAYCE------D
YKTKKR--DEF
>gi|340369653|ref|XP_003383362.1| PREDICTED: eukaryotic translation initiation factor 5B-like [Amphimedon queenslandica]
KK---PDEIDV---LKDEA------ASM-MSSLLNTF--------------KLSERGVFV
QASTLGSLEALVDFLKS---S----------KIPYAGVNIGPVHKKDVMKTSVML--E--
-R--DSQWACILAFDVKVERDAQELADSL--GVRIFTADIIYHLFDSFMKYRE------E
LKERKR--REN
>gi|198432933|ref|XP_002127409.1| PREDICTED: similar to Eukaryotic translation initiation factor 5B (eIF-5B) (Translation initiation factor IF-2) [Ciona intestinalis]
RG---EEEIEI---CKEEV------QAE-VNEALKAI--------------KLQERGVFV
QASTLGSLEALLEFLKQ---S----------KIPYAGIGIGPVHRKDIMKASVML--E--
-H--DDQWAVILAFDVKVEREAQEIAENL--GVKIFTADIIYHLFDAFMQHRE------D
LKKRKQ--DEF
>gi|391336572|ref|XP_003742653.1| PREDICTED: eukaryotic translation initiation factor 5B-like [Metaseiulus occidentalis]
HN---NDEIEF---LKEEI------ARS-LKEVMGSF--------------KLHDKGVYV
QASTLGSLEALLVFLKD---S----------KIPYFGIRIGPVVKKDVIKASVML--E--
-H--DSQYAVILAFDVKVERDAQELADHT--GVKIFSADIIYHLFDKFMAHRE------E
LRQKKR--EEF
>gi|339243339|ref|XP_003377595.1| putative elongation factor Tu GTP binding domain protein [Trichinella spiralis]
KK---ESEIEE---LKEEL------SNS-LKKILQAV--------------KLSERGVYV
QASTLGSLEALLEFLRA---Q----------KIPYFGVNIGPVHKRDVVKVSTML--E--
-H--DPQWAVILAFDVKVDRDAQQMADEL--EVKIFQADIIYHLQDAFLKYRE------E
LKQKKR--QEF
>gi|324501293|gb|ADY40578.1| Eukaryotic translation initiation factor 5B [Ascaris suum]
NK---EDELDV---LKEES------EAQ-LSKALMAI--------------KKKPEGVYV
QASTLGSLEALLEFLKA---Q----------KIPYSNVNIGPVHKKDVQKAAAML--E--
-R--KEEYACILAFDVRVDRDAEQFAATE--GVRIFSADIIYHLEESFLKYRE------E
LRLRRR--REN
>gi|402593466|gb|EJW87393.1| elongation factor Tu GTP binding domain-containing protein [Wuchereria bancrofti]
NR---EDELLV---LKEDC------EAQ-LCKALMAI--------------KKKPEGVYV
QASTLGSLEALLEFLRT---Q----------KIPYSNVNIGPVHKKDVQKAAAML--E--
-R--KEEYACILAFDVRVDREVEQFAVSE--GVRIFSADIIYHLEDSFLKYRE------E
LRLKRR--QQN
>gi|393907508|gb|EFO26683.2| elongation factor Tu GTP binding domain-containing protein [Loa loa]
NR---EDELLV---LKEDC------EAQ-LSKALMAI--------------KKKPEGVYV
QASTLGSLEALLEFLRT---Q----------KIPYSNVNIGPVHKKDVQKAAAML--E--
-R--KEEYACILAFDVRVDREVEQFAATE--GVRIFSADIIYHLEDSFLKYRE------E
LKLKRR--RQN
>gi|170591761|ref|XP_001900638.1| Elongation factor Tu GTP binding domain containing protein [Brugia malayi]
NR---EDELLV---LKEDC------EAQ-LCKALMAI--------------KKKPEGVYV
QASTLGSLEALLEFLRT---Q----------KIPYSNVNIGPVHKKDVQKAAAML--E--
-R--KEEYACILAFDVRVDREVEQFAVSE--GVRIFSADIIYHLEDSFLKYRE------E
LRLKRR--RQN
>gi|212656558|ref|NP_497536.2| Protein IFFB-1 [Caenorhabditis elegans]
DR---EDEVDY---LRHEA------DRQ-LANALHAI--------------RKKPEGVYV
QASTLGSLEALLEFLKS---Q----------NIPYSNVNIGPVHKKDVQKASAMK--E--
-H--KAEYACVLAFDVKVEREAQIFADHE--GVKVFQADIIYHLQDAFLKYRE------E
LKEKAR--RDN
>gi|326436198|gb|EGD81768.1| eukaryotic translation initiation factor 5B [Salpingoeca sp. ATCC 50818]
HT---PEEEEV---YKEEA------ERL-LEDTLNAI--------------KTVEKGVCV
QASTLGSLEALLEFLRT---E----------KIPVSAVNIGPVHRRDVTRCTIQL--Q--
-R--DPKYACILAFDVPVDADAKRYAARE--GIRIFEADIIYHLEESFRKHME------E
VKQQLR--ERY
>gi|320163631|gb|EFW40530.1| eIF5B-PB [Capsaspora owczarzaki ATCC 30864]
YD---EDEVEV---LKEDV------TAD-LARSLNQI--------------KTVDRGVLV
QASTLGALEALMEFLRT---S----------KIPVSAVSVGPVHRKDVMRAKVQL--E--
-K--DPTYAIIMAFDVKVDKEVREFADKE--SIKIFTADIIYHLFDQFTAYME------Q
LKQKAK--DEN
>gi|313244585|emb|CBY15337.1| unnamed protein product [Oikopleura dioica]
RK---DDEVEY---FKGEL------EEE-IGDALDAI--------------RTSSEGVYV
QASTLGSLEALLEFLRT---E----------KVKYSNINIGPVNKRDIMKASTML--E--
-H--DEKYGVVLAFDVPVTRDAQELAESFKPPIKIFTANIIYHLTDMFEKHLK------D
QKKRRQ--EEL
>gi|168053025|ref|XP_001778939.1| predicted protein [Physcomitrella patens subsp. patens]
GP---EDDVED---MKDEA------MQD-MRNVMSRI--------------DKSGEGVCV
QASTLGSLEALLEFLKSP-AV----------KIPVSGISIGPVHKKDVMRASVML--E--
-RK-RKEFATILAFDVKVTAEAKELAEEV--GVRIFTADIIYHLFDQFTAYMN------S
VKEEKR--KEA
>gi|301091127|ref|XP_002895755.1| eukaryotic translation initiation factor 5B [Phytophthora infestans T30-4]
GP---DDDVEE---LKDSV------MSD-LTGILDSV--------------KATRRGVMV
QASTLGALEALLEFLR----T-------CDPPIPVSCVNIGPVHKKDVMRASVQL--E--
-H--QPEFATILAFDVKVHSDATELATEL--GVRIFTADIIYHLFDQFTAYMD------N
FRMARR--EEF
>gi|145345087|ref|XP_001417054.1| predicted protein [Ostreococcus lucimarinus CCE9901]
DP---EDDEME---LREEV------LSD-MKGVLARV--------------DKSGEGVYV
QASTLGSLEALLEFLKSD-AV----------KIPVAGIAIGPVNKRDVMGASVMH--E--
-RK-KPEYATILAFDVPVTKEAHAMGEEL--NVRIFTADIIYHLFDQFTAYME------K
VKADKR--EAA
>gi|302761168|ref|XP_002964006.1| hypothetical protein SELMODRAFT_166557 [Selaginella moellendorffii]
GE---DEDVET---IKEEA------MKD-MKSVMGRI--------------DKSGEGVCV
QASTLGSLEALLEFLKTP-DV----------NIPVSGISIGPVHKKDIMRASVML--E--
-RK--KEYATILAFDVKVTPEARELAEEL--GVKIFTADIIYHLFDQFTAYLK------N
TREEKR--RDT
>gi|325183049|emb|CCA17504.1| predicted protein putative [Albugo laibachii Nc14]
GP---DDDVEE---LKDSV------MSD-LTGILDSV--------------KATKRGVMV
QASTLGALEALLEFLR----T-------CDPPIPVACVNIGPVHKKDVMRASVQL--E--
-H--QPEYATVLAFDVKVHHDATELAQEL--GVRIFTADIIYHLFDQFTAYMD------N
FRSTRR--EEV
>gi|307109358|gb|EFN57596.1| hypothetical protein CHLNCDRAFT_34815 [Chlorella variabilis]
GP---DDDVED---LKDAV------MED-MQDIFSSV--------------DKTGEGVCV
QASTLGSLEALLEFLRSD-DV----------KIPVSSINIGPINKKDIMRANAMI--E--
-RG-HKKFGVILAFDVPVTREAGALAEQM--GVRIFTADIIYHLFDQFTAYLK------Q
VKEEEQ--EAA
>gi|326497395|dbj|BAK05787.1| predicted protein [Hordeum vulgare subsp. vulgare]
RP---DADIED---LKDAV------MEE-MSRVRNRI--------------DKSGEGVYV
QASTLGSLEALTEFLKS---P--------AVNIPFCDFSIGPVHKKDVMKASVML--E--
-R--KKEYATILAFDVKVMPDARDLAEES--GVKIFVADIIYHLFDQFTAYIK------N
IREEKK--KDS
>gi|384245942|gb|EIE19434.1| P-loop containing nucleoside triphosphate hydrolase protein [Coccomyxa subellipsoidea C-169]
HK---PEDLEG---LKLLA------MKD-MEDIFKSV--------------DRSGEGVCV
QASTLGSLEALLEFLRS---P--------AVKIPVSGIAIGPIHKKDVMRASVML--E--
-KG-RQKFAVILAFDVPVTKEARELAESL--GVRIFTADIIYHLFDHGRGCLKRCGGGVQ
VKDAEQ--EAA
>gi|359493041|ref|XP_002267014.2| PREDICTED: uncharacterized protein LOC100242745 [Vitis vinifera]
GP---DDDLED---IKEAA------MED-MKSVLSRI--------------DKSGEGVYV
QASTLGSLEALLEFLKS---P--------AVSIPVSGIGIGPVHKKDVMKASVML--E--
-K--KKEYATILAFDVKVTPEARELADDM--GVKIFIADIIYHLFDQFKAYID------N
LKEEKK--REA
>gi|23452071|gb|AAN32916.1| translation initiation factor [Pisum sativum]
KP---DDDLEH---IKTAA------LED-VESVLSRI--------------DRSGEGVCV
QASTLGSLEALLEFLKTP-AV----------NIPVSAISIGPVHKKDVMKASVML--E--
-KK--REYSTILAFDVKVTPEARELADEL--GVKIFIADIIYHLFDQFKAYME------N
IKDEKK--KES
>gi|48475233|gb|AAT44302.1| putative translation initiation factor IF-2 [Oryza sativa Japonica Group]
KP---DDDLDR---LKDAV------MEE-MTRVRNRI--------------DKSGEGVYV
QASTLGSLEALTEFLKS---P--------AVNIPFCDFSIGPVHKKDVMKASVML--E--
-R--KKEYATILAFDVKVMPDARDLAEES--GVRIFVADIIYHLFDQFTAYIK------N
LREEKK--KES
>gi|393246664|gb|EJD54173.1| hypothetical protein AURDEDRAFT_110746 [Auricularia delicata TFB-10046 SS5]
GP---DDDEEV---LRDAV------MTD-LTTLVNSV--------------DKSERGVCV
QASTLGSLEALLDFLKV---S----------KIPVSGIGIGPVHKKDIMRAATMV--E--
-KA--KELAVILCFDVTVDREVEKLAEEM--GVRLFKADIIYHLFDAFTAYNN------E
ITEAKR--KDA
>gi|303272127|ref|XP_003055425.1| translation initiation factor [Micromonas pusilla CCMP1545]
NK---EDDLDE---LKDEV------LSD-MKNVFSRV--------------DKSGEGVYV
QASTLGSLEALLEFLKS---D--------AVKIPVAGIAIGPVNKRDVMGASVMH--E--
-RK-RPEFATILAFDVKVTEEATRMANEL--NVKVFTADIIYHLFDQFTAYMA------E
IKAKKK--AAA
>gi|296422966|ref|XP_002841028.1| hypothetical protein [Tuber melanosporum Mel28]
GP---DDDEED---LEMEV------MSD-LEQLFSKV--------------SKSGAGVAV
QASTLGSLEALLAFLKS---S----------SIPVSTISIGPVYKRDVMRAGTML--E--
-KH--KEYAVMLCFDVKVDKEAQAYADEV--GVKLFTAEIIYHLFDAFTAYKK------E
MSEQRK--RES
>gi|357161073|ref|XP_003578970.1| PREDICTED: uncharacterized protein LOC100838847 [Brachypodium distachyon]
RP---EEDIEN---LKDAV------MKE-MATVRNRI--------------DKSGEGVYV
QASTLGSLEALTEFLKS---P--------AVNIPFCDFSIGPVHKKDVMKASVML--E--
-R--KKEYATILAFDVKVMPDARDLAEES--GVRIFVADIIYHLFDQFTAYIK------N
LREEKK--KES
>gi|356535804|ref|XP_003536433.1| PREDICTED: eukaryotic translation initiation factor 5B-like [Glycine max]
KP---DDDLED---VKESA------MED-MRSVMSRI--------------DRTGEGVCV
QASTLGSLEALLEFLKT---P--------EVSIPVSGISIGPVHKKDVMKASVML--E--
-K--KREYAAILAFDVKVTPEARELADEL--GVKIFIADIIYHLFDQFKAYID------N
IKEEKK--REA
>gi|42563275|ref|NP_177807.3| translation initiation factor eIF-5B [Arabidopsis thaliana]
GP---DDDIEA---IKESA------MED-MESVLSRI--------------DKSGEGVYV
QASTLGSLEALLEYLKS---P--------AVKIPVSGIGIGPVHKKDVMKAGVML--E--
-R--KKEYATILAFDVKVTTEARELADEM--GVKIFCADIIYHLFDLFKAYIE------N
IKEEKK--KES
>gi|389744322|gb|EIM85505.1| hypothetical protein STEHIDRAFT_80921 [Stereum hirsutum FP-91666 SS1]
GP---DDDEDD---LREEV------MSD-LTSLLNSI--------------DKSGRGVCV
QASTLGSLEALLDFLKS---S----------KIPVSGINIGPVHKKDVMRAGTML--E--
-KA--RELACILCFDVTVDKDAERMAEEM--GIRLFKADIIYHLFDAFTAYNA------E
ILEAKR--KDA
>gi|167376130|ref|XP_001733874.1| eukaryotic translation initiation factor 5B [Entamoeba dispar SAW760]
NN---DEELEE---VKTEV------QSE-FEKFQVSV---------------SEKEGVFV
QASSLGSLEALLKFLKD---S----------KIPVSGVGLGPIFKKDVMKTLIMK--E--
-K--NPDYAIIMAFDVTVDKEARDYAAEE--GILIFTANIIYHLFDQFNEHMK------K
LEEQKRIAAEN
>gi|209878374|ref|XP_002140628.1| eukaryotic translation initiation factor 5B [Cryptosporidium muris RN66]
PKNATEEDIEL---LREQV------MED-MGEVFRSV--------------DKSGNGVYV
MASTLGSLEALLVYLKS---C----------NIPVVALNIGTVHKLDVRRASIMH--E--
-RG-HPEMAVILAFDIKVEAEAELEAKKL--GVKIMKANIIYHLCDMFTKYYT------D
VQEEKR--KEK
>gi|395330731|gb|EJF63114.1| hypothetical protein DICSQDRAFT_103670 [Dichomitus squalens LYAD-421 SS1]
GP---DDDEEE---LMDEV------MSD-LTTLLNSI--------------DKSGRGVCV
QASTLGSLEALLDFLKS---S----------KIPVSGINIGPVHKRDVMRAATML--E--
-KA--KELACILCFDVTVDRDAERLAEEM--GIRLFKADIIYHLFDAFTAYNN------E
IMEAKR--KDA
>gi|328854825|gb|EGG03955.1| hypothetical protein MELLADRAFT_49335 [Melampsora larici-populina 98AG31]
TD---DDDEED---LKEEV------MGD-LTNLMNNI--------------DKSGRGVCV
QASTLGSLEALLEFLRT---S----------KIPVSGINIGPVYKRDVMRAGTML--E--
-KA--KELAVLLAFDVPIDKDAEKLAEET--GVKIFKADIIYHLFDAFTAYNA------N
ILEAKR--IDS
>gi|401410612|ref|XP_003884754.1| GM14051, related [Neospora caninum Liverpool]
EE---DDDIED---LKEEV------MSD-MGSIFKSV--------------DRSGSGVYV
MASTLGSLEALLVFLQE---S----------KIPVFGVNIGTVQKKDVKKASIMR--E--
-KG-RPDLSVILAFNVKVDPEAEKEAKTL--GVKIMTAEIIYHLFDEFTAYFQ------S
MKEEKK--KEV
>gi|345563505|gb|EGX46505.1| hypothetical protein AOL_s00109g77 [Arthrobotrys oligospora ATCC 24927]
GP---DDDEED---LCEEV------MSD-LEGLLNKV--------------EKSGKGVCV
QASTLGSLEALLDFLSV---S----------KIPVMSISIGPVYKRDVMRAGTML--E--
-KN--KEFAVMLCFDVKVDKEAQAYADEV--GVKLFTADIIYHLFDSFTAYQK------D
LLEQKR--KET
>gi|403414332|emb|CCM01032.1| predicted protein [Fibroporia radiculosa]
GP---DDDEDD---LMDEV------MSD-LTTLLNSI--------------DKSGRGVCV
QASTLGSLEALLDFLKS---S----------KIPVSGINIGPVHKKDVMRAATML--E--
-KA--KELAVILCFDVPVDKDADRLAEEM--GLRIFKADIIYHLFDAFTAYNN------E
IMEAKR--RDA
>gi|66475520|ref|XP_627576.1| Fun12p GTpase; translation initiation factor IF2 [Cryptosporidium parvum Iowa II]
SKNSTPEEIES---LKEEV------MKD-MGDIFSSV--------------DRTGNGVYV
MASTLGSLEALLVFLKS---S----------NIPVVALNIGTVHKSDVRRASIMH--E--
-RG-FPEMAVILAFDIKVDAEAEVEAKKL--NVRIMKANIIYHLCDMFTKYYS------D
VQEEKK--KEK
>gi|357443693|ref|XP_003592124.1| Eukaryotic translation initiation factor 5B [Medicago truncatula]
KP---DDDLEY---IKKAA------LED-VESVLSRI--------------DRSGEGVCV
QASTLGSLEALLEFLKT---P--------EVNIPVSAINIGPVHKKDVMKASVML--E--
-K--KREYATILAFDVKVTPEARDLAEEL--GVKIFIADIIYHLFDQFKAYMD------N
IKEEKK--KES
>gi|237842925|ref|XP_002370760.1| translation initiation factor IF-2, putative [Toxoplasma gondii ME49]
EE---DDDIED---LKEEV------MSD-MGSIFKSV--------------DRTGSGVYV
MASTLGSLEALLVFLQE---S----------KIPVFGVNIGTVQKKDVKKASIMR--E--
-KG-RPDLSVILAFNVKVDPEAEKEAKTL--GVKIMTAEIIYHLFDEFTAYFQ------S
MKEEKK--KAV
>gi|402225944|gb|EJU06004.1| hypothetical protein DACRYDRAFT_19346 [Dacryopinax sp. DJM-731 SS1]
GP---DDDEDD---LTEEV------MTD-LTSLLSSI--------------DKSGRGVCV
QASTLGSLEALLDFLKV---S----------RIPVSGINIGPVHKKDIMRAATML--E--
-RQ--RELACILAFDVPVDKDADKMAEEL--GVRIFKADIIYHLFDAFTAYNA------E
MTEARR--RDA
>gi|294896516|ref|XP_002775596.1| eukaryotic translation initiation factor 5B, putative [Perkinsus marinus ATCC 50983]
RP---GDDAEE---VKRRA------MAD-YKAVVNEF--------------KKAPEGVYV
KASTLGSLEALLDFLKT---S----------SIPVNQVGIGEVHLMDVRKASIML--E--
-K--KKEYAVILAFDVKVSPEARDEAEKL--GVKIMTAEIIYHLFDQFTAYMN------Q
IKEEKR--QQV
>gi|302672415|ref|XP_003025897.1| hypothetical protein SCHCODRAFT_80123 [Schizophyllum commune H4-8]
GP---DDDEDD---LRDEV------MSD-LTSLLNSI--------------DKSGRGVCV
QASTLGSLEALLDFLKS---S----------KIPVSGINIGPVHKRDVMRSATML--E--
-KA--KELACILCFDVPVDKDAERMAEEM--GIRLFKADIIYHLFDAFTAYNS------E
IVEAKR--RDA
>gi|213408192|ref|XP_002174867.1| translation initiation factor IF2 [Schizosaccharomyces japonicus yFS275]
GP---DDDEEE---LADEI------MED-LEDLLGRI--------------DTSGVGVSV
QASTLGSLEALLEFLKQ---M----------EIPVSSVSVGPVYKKDIMRSATML--E--
-KA--PEYAIMLCFDVKIDKDAEELAEQM--GIKIFSANIIYHLFDAFTAHQK------Q
LMEKKR--EEG
>gi|299747178|ref|XP_002911138.1| GTPase [Coprinopsis cinerea okayama7#130]
GP---DDDEEE---LKDEV------MSD-LTSLLNSI--------------DKSGRGVCV
QASTLGSLEALLDFLKD---S----------KIPVSGINIGPVHKRDVMRAGTML--E--
-KA--KELAVILAFDVPVDKDAERLAEEM--GIRIFTANIIYHLFDSFTAYNA------Q
IMEAKR--ADA
>gi|242209097|ref|XP_002470397.1| eukaryotic translation initiation factor 5B [Postia placenta Mad-698-R]
GP---DDEEED---LMEEV------MSD-LTTLLNSI--------------DKSGRGVCV
QASTLGSLEALLDFLKS---S----------KIPVSGINIGPVHKKDVMRAATML--E--
-KA--KELACILCFDVTVDKDAERLAEEM--GIRLFKADIIYHLFDAFTAYNA------E
ITEAKR--RDA
>gi|224120424|ref|XP_002318326.1| predicted protein [Populus trichocarpa]
GR---DDDVED---VKESA------MED-MKSVMSRI--------------DKTGEGVYV
QASTLGSLEALLEFLKS---P--------AVSIPVSGIGIGPVHKKDVMKSSVML--E--
-K--KKEYATILAFDVKVTPEARELADEL--GVKIFIADIIYHLFDQFKAYIQ------N
LKEEKK--REA
>gi|392569077|gb|EIW62251.1| hypothetical protein TRAVEDRAFT_144706 [Trametes versicolor FP-101664 SS1]
GP---DDDEED---LMDEV------MSD-LTTLLNSI--------------DKSGRGVCV
QASTLGSLEALLEFLRT---S----------KIPVSGINIGPVHKKDVMRSASML--E--
-KA--KELACILCFDVPVDRDAERLAEEM--GIRLFKADIIYHLFDAFTAYNA------E
IMEAKR--KDA
>gi|392592833|gb|EIW82159.1| hypothetical protein CONPUDRAFT_81697 [Coniophora puteana RWD-64-598 SS2]
GP---DDDEDD---LRDEV------MSD-LTSLLNSI--------------DKSGRGVCV
QASTLGSLEALLDFLKV---S----------KIPVSGINIGPVHKKDIMRCATML--E--
-KA--KELAVILAFDVPVDRDADRLAEEM--GIRIFKADIIYHLFDAFTAYNN------E
IMEAKR--RDA
>gi|399217750|emb|CCF74637.1| unnamed protein product [Babesia microti strain RI]
KD---GDDIEE---LKVEV------MRD-ISSIFDCV--------------DRSGVGVYL
MASTLGSLEALLQFING---Q----------KIPVFCVNIGAVQKKDVKKASIML--E--
-K--RPEYAAILAFDVKVTQDAEKEAETL--GVTIFCADIIYHLSDRFTKHME------E
QRELYR--KQR
>gi|290992156|ref|XP_002678700.1| predicted protein [Naegleria gruberi]
KN---GDDLDA---MKEEV------MAD-LKEVLNRI--------------STTGKGVFV
QASTLGSLEALLEFLKS---E----------HIPVSGINIGPVHKKDIIRTSVML--E--
-N--APEYAVLLAFDVKITADAKEEADKL--GITIFSADIIYHLFDRFKEHKA------K
KLEEKK--KAA
>gi|300120271|emb|CBK19825.2| unnamed protein product [Blastocystis hominis]
RN---NDELPM---LQEQV------QEE-LESARRLL--------------KVDGEGVFV
QASTLGSLEALLEFLSS---L--------DPPIPVGAFNIGPISKRDVIQASVML--E--
-K--KREYAVILAFDVKVTPNGAQMAKEL--GVRIFSADIIYHLFDQFTNYIK------E
LRDKDT--EVK
>gi|164659700|ref|XP_001730974.1| hypothetical protein MGL_1973 [Malassezia globosa CBS 7966]
TR---DDEEEL---LREEV------MSD-LTTLLNSV--------------DKSGKGVCV
QASTLGSLEALLEFLRV---S----------KIPVSGINIGPVYKRDVMRCATML--E--
-KA--RELACILCFDVPVDKEAERLADEL--GVKLFTADIIYHLFDSFMAYSA------E
IMESKK--RDA
>gi|19114130|ref|NP_593218.1| translation initiation factor IF2 (predicted) [Schizosaccharomyces pombe 972h-]
GP---DDDEED---LAEEI------MED-LENLLGRI--------------DTSGIGVSV
QASTLGSLEALLEFLKQ---M----------KIPVASVNIGPVYKKDVMRCATML--E--
-KA--KEYALMLCFDVKVDRDAEDLAEQL--GVKIFSANVIYHLFDAFTAHQK------K
ILEQKR--EES
>gi|170106365|ref|XP_001884394.1| predicted protein [Laccaria bicolor S238N-H82]
GP---DDDEED---LKEEV------MSD-LTSLLNNI--------------DKSGRGVCV
QASTLGSLEALLDFLKT---S----------KIPVSGINIGPVYKRDVMRAGTML--E--
-KA--KELACILCFDVPIDKEAERLAEEM--GIRLFKADIIYHLFDSFKAYND------E
ITEAKR--RDA
>gi|390594979|gb|EIN04387.1| hypothetical protein PUNSTDRAFT_122924 [Punctularia strigosozonata HHB-11173 SS5]
GP---DDDEDD---LKDEV------MGD-LTNLLSSI--------------DKSGRGVCV
QASTLGSLEALLDFLKV---S----------KIPVSGINIGPVHKKDVMRAATML--E--
-KA--KELACMLCFDVPVDRDAERLAEEL--GIKIFKADIIYHLFDAFTAYNA------E
IMEAKR--RDA
>gi|393215318|gb|EJD00809.1| hypothetical protein FOMMEDRAFT_21315 [Fomitiporia mediterranea MF3/22]
GP---DDDEED---LKEEV------MGD-LTTLLNSV--------------DKSGRGVCV
QASTLGSLEALLDFLKV---S----------KIPVSGINIGPVHKRDVMRCATVL--E--
-KA--KELACILCFDVPVDKDADRLAEEL--GIKLFKADIIYHLFDAFTAYNA------E
ITEAKR--RDA
>gi|343427969|emb|CBQ71494.1| probable GTPase/general translation initiation factor eIF2 [Sporisorium reilianum SRZ2]
GP---DDDEED---LKDEV------MSD-LSSLMNSI--------------DTSGRGVCV
QASTLGSLEALLEFLRV---S----------KIPVNGINIGPVFKKDVVRCSTML--E--
-KA--KELAVILAFDVPVDKEAEKLAEEL--GIKIFTAKIIYHLENDFTKYHK------E
VMDGKK--KEA
>gi|388581389|gb|EIM21698.1| P-loop containing nucleoside triphosphate hydrolase protein [Wallemia sebi CBS 633.66]
GE---DDDEEE---LMEEV------MGD-LQTLLSSI--------------DKSGRGVCV
QASTLGSLEALLDFLRA---S----------EIPVSGINIGPVYRKDVLRAGVMI--E--
-KA--KEFATILAFDVPVDKEAEKYADEV--GVKIFKADIIYHLFDQFTAYNK------S
IVEEKR--KEA
>gi|336373136|gb|EGO01474.1| hypothetical protein SERLA73DRAFT_158777 [Serpula lacrymans var. lacrymans S7.3]
GP---DDDEEE---MLDEI------MSD-LTSLLNSI--------------DKSGRGVCV
QASTLGSLEALLDFLKV---S----------KIPVSGINIGPVHKKDVMRCATML--E--
-KA--KELAVILCFDVPVDRDADRMAEEM--GIRIFKADIIYHLFDAFTAYNN------E
IMEAKR--KDA
>gi|331238663|ref|XP_003331986.1| translation initiation factor IF-2 [Puccinia graminis f. sp. tritici CRL 75-36-700-3]
TE---DDDEED---LKEEV------MGD-LTNLMSNI--------------DKSGRGVCV
QASTLGSLEALLEFLRT---S----------KIPVSGINIGPVYKRDVMRAGTML--E--
-KA--KELAVLLAFDVPIDKDAEKLAEET--GVRIFKADIIYHLFDAFTAYNA------D
IMEAKR--IDS
>gi|255940774|ref|XP_002561156.1| Pc16g08350 [Penicillium chrysogenum Wisconsin 54-1255]
GP---DDDEED---LEEEV------MSD-LESLLSRV--------------STDQRGVTV
QASTLGSLEALLEFLKV---S----------KIPVANISIGPVYRRDVMMAGTML--E--
-KS--KEHAVMLCFDVKVDKEAMAYANEI--GVKIFTADIIYHLFDAFTAHMA------Q
ITEQRK--EEA
>gi|71024283|ref|XP_762371.1| hypothetical protein UM06224.1 [Ustilago maydis 521]
GP---DDDEED---LKDEV------MSD-LSSLMNSI--------------DTSGRGVCV
QASTLGSLEALLEFLRV---S----------KIPVNGINIGPVFKKDVVRCSTML--E--
-KA--KELAVILAFDVPVDKEAEKLAEEL--GIKIFTARIIYHLENDFTRYHK------E
VMDGKK--KEA
>gi|86170667|ref|XP_966060.1| translation initiation factor IF-2, putative [Plasmodium falciparum 3D7]
NN---IEEEEE---YKKKV------MTD-VSDVFNHV--------------DKTGVGLYV
MASTLGSLEALLIFLND---S----------KIPVFGVNIGTIQKKDVKKASIMR--E--
-KG-RPEYAVILAFDVKIDPEAEKEAALL--GVEIMQRDIIYHLFDSFTAYLK------K
IEEEKK--QSK
>gi|254565589|ref|XP_002489905.1| GTPase [Komagataella pastoris GS115]
GP---DDDEEE---LKDTV------MDD-LTGLLDSV--------------DSSGHGVTV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKATTML--E--
-KD--KEYAVMLCFDVKIDKEAEQYADEQ--GIKIFNADVIYHLFDAFSAYQA------K
LLEQRR--KDF
>gi|58263410|ref|XP_569115.1| GTPase [Cryptococcus neoformans var. neoformans JEC21]
QD---DDEVEA---FKDMA------MDD-LTSLGRFV--------------TKSGKGVWV
QASTLGSLEALLTFLEQ---M----------KIPVFNFGIGPVHKSTIVKAGTML--D--
-KA--PEYAVILAFDVQIEKEAQELAQKA--GMKIFSAMIIYHLFDAFTKYMS------E
VQEAKR--KEA
>gi|378731605|gb|EHY58064.1| translation initiation factor IF-2 unclassified subunit [Exophiala dermatitidis NIH/UT8656]
GP---EDDEED---LCEEV------MAD-LQQLLSKV--------------SKDNRGVSV
QASTLGSLEALLEFLKQ---M----------KIPVANISIGPVYKRDVMMAGTML--E--
-KA--KQYAVMLCFDVKVDKEAQQYADEN--GIKIFTADIIYHLFDDFTKHMA------K
LQEQKK--EES
>gi|255574361|ref|XP_002528094.1| translation initiation factor if-2, putative [Ricinus communis]
GP---DDNLED---IKEAA------MED-VRSVMNRI--------------EKRDEGVYV
QASTLGSLEALLEFLKS---P--------AVGIPVSGIGIGPVHKKDVMKASVML--E--
-K--KKEYATILAFDVKVSQETRELADDL--GVKIFMADIIYHLFDQFKAYID------N
LKEEKK--KEA
>gi|171688566|ref|XP_001909223.1| hypothetical protein [Podospora anserina S mat+]
GP---DDDEDD---LEEEV------EAD-LASLFSRV--------------EKTGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQCGVML--E--
-KS--PDLAVMLCFDVKVDKEAQQYADEQ--GIKIFTADIIYHLFDNFTKHQA------E
QLEKKK--EES
>gi|344300655|gb|EGW30976.1| hypothetical protein SPAPADRAFT_62879 [Spathaspora passalidarum NRRL Y-27907]
GE---DDDEEE---IMDEV------MDD-LTGLLDSV--------------DTSGKGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKATTML--E--
-KA--PELAVMLCFDVKIDKEAEQYADEQ--NIKIFNADIIYHLFDAFTAYQQ------K
LLEARR--KEF
>gi|303322711|ref|XP_003071347.1| Eukaryotic translation initiation factor 5B, putative [Coccidioides posadasii C735 delta SOWgp]
GP---DDDEED---LEDEV------MSD-LENLLSKV--------------SKDNRGVSV
QASTLGSLEALLEFLKV---S----------KIPVANISIGPVYKRDVMRAGTML--E--
-KA--KQFAVMLCFDVKVDREAQAYADEV--GVKIFTADIIYHLFDDFTKHME------E
LSTKKK--EEA
>gi|330922464|ref|XP_003299850.1| hypothetical protein PTT_10932 [Pyrenophora teres f. teres 0-1]
GP---NDDEED---LMDEV------MGD-LAHLLSKV--------------SKTGRGVSV
QASTLGSLEALLEFLRV---S----------KIPVSTISIGPVFRKDVLRAGTML--E--
-KA--KEYAVMLCFDVKVDKEAKAYAEEI--GVKIFEADIIYHLFDKFTAHMK------Q
LEEQRK--EES
>gi|336471754|gb|EGO59915.1| hypothetical protein NEUTE1DRAFT_145803 [Neurospora tetrasperma FGSC 2508]
GP---DDDEDD---LEDEV------EAD-LASLFSRV--------------EKSGRGVSV
QASTLGSLEALLDFLKE---C----------KIPVANVGIGPVYKRDVMQCGIML--E--
-KA--PDYAVMLCFDVKVDKEAQEYADQQ--GVKIFTADIIYHLFDSFTKHMD------E
LLEKKK--EES
>gi|296815262|ref|XP_002847968.1| eukaryotic translation initiation factor 5B [Arthroderma otae CBS 113480]
NH---DDDEED---LTDEV------MSD-LENLLSKV--------------SRDNRGVAV
QASTLGSLEALLEFLRT---S----------KIPVANISIGPVYKRDVMRAGAML--E--
-KA--KQYAVMLCFDVKVDKEAQAYADEN--GIKIFTADIIYHLFDDFTKHME------E
LAAQRK--EES
>gi|366993797|ref|XP_003676663.1| hypothetical protein NCAS_0E02340 [Naumovozyma castellii CBS 4309]
GP---DDDEEE---MMDDV------MDD-LTGLLDSV--------------DTSGKGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKAGTML--E--
-RA--PEYAVMLCFDVKVDKEAEQYAEQE--GIKIFNADIIYHLFDAFTAYQE------K
LLEDRR--KDF
>gi|403215813|emb|CCK70311.1| hypothetical protein KNAG_0E00430 [Kazachstania naganishii CBS 8797]
GP---EDDEDE---LMDDV------MDD-LTGLLDLV--------------DSSGRGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKASAML--E--
-KA--PEYAVMLCFDVKIDKEAEQYAEQE--GVKIFNADIIYHLFDAFTAYQE------Q
LLEQRR--KDF
>gi|156085667|ref|XP_001610243.1| translation initiation factor IF-2 [Babesia bovis T2Bo]
ED---DDDIEQ---LCEDV------MQD-MSSIFGNV--------------NRTGVGVYV
MASTLGSLEALLQFLTD---K----------KIPVFSVNIGTVQKKDVKKASIMR--E--
-KG-YPEYSVILAFDVKCATEAEKEAQVL--GVKIMSADIIYHLLDSFVKYLE------E
TQEQKK--QSR
>gi|302658217|ref|XP_003020815.1| hypothetical protein TRV_05091 [Trichophyton verrucosum HKI 0517]
NH---DDDEED---LTDEV------MSD-LENLLSKV--------------SRDNRGVAV
QASTLGSLEALLEFLRT---S----------KIPVANISIGPVYKRDVMRAGAML--E--
-KA--KQYAVMLCFDVKVDKEAQAYADEN--GIKIFTADIIYHLFDDFTKHME------E
LAAQRK--EES
>gi|190349184|gb|EDK41789.2| conserved hypothetical protein [Meyerozyma guilliermondii ATCC 6260]
NE---GDDEEE---IMEEV------MDD-LTGLLDSV--------------DTSGKGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVFKRDVMKATTML--E--
-KA--PEYAVMLCFDVKVDKEAELYAEEQ--NIKIFNADIIYHLFDAFTAYQE------K
LMEIRR--RDF
>gi|340513971|gb|EGR44243.1| hypothetical protein TRIREDRAFT_70795 [Trichoderma reesei QM6a]
GP---DDDEDE---IVDEV------ESD-LANLLSRV--------------ETSGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQCGIML--E--
-KA--PDYAVMLCFDVKVDKEAQAYADDQ--GIKIFQADIIYHLFDNFTKHMD------E
MLEKKK--EES
>gi|403221761|dbj|BAM39893.1| translation initiation factor IF-2 [Theileria orientalis strain Shintoku]
GD---ADDVDE---LCNEV------MSD-MSSIFDCI--------------DRTGVGVYV
MASTLGSLEALLHFLND---K----------KIKIFGVNIGPVQKKDVKKASIMR--E--
-KG-HPEYSTILAFDIKVTPDAEKEAELL--GVKLLTADIIYHLLDSFLAYME------A
MQEAKK--QEQ
>gi|336267862|ref|XP_003348696.1| hypothetical protein SMAC_01718 [Sordaria macrospora k-hell]
GP---DDDEDD---LEDEV------EAD-LASLFSRV--------------EKSGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQCGIML--E--
-KA--PDYAVMLCFDVKVDKEAQEYADQQ--GVKIFTADIIYHLFDSFNKHMD------E
LLEKKK--EES
>gi|225678071|gb|EEH16355.1| eukaryotic translation initiation factor 5B [Paracoccidioides brasiliensis Pb03]
GP---DDDEED---LEDEV------MSD-LENLLSKV--------------SKDNRGVSV
QASTLGSLEALLEFLRV---S----------KIPVANISIGPVYKRDVMRAGTML--E--
-KA--KQFAVMLCFDVKVDKEAQAYADEV--GIKIFTADIIYHLFDDFTKHMQ------Q
ITEQKK--EES
>gi|403350465|gb|EJY74695.1| hypothetical protein OXYTRI_04044 [Oxytricha trifallax]
TN---EEEIET---YKAQI------QDDLVDIMDKYV--------------DKTASGVCV
QASTLGSLEALLEFLKT---M----------KIPVTAINIGPVHKKDILKAMKSIAGE--
-FK-EREFATVLAFDVKITPEAQQFAEEN--EIKIFTANIIYHLFDQFTEYVK------K
CRDERK--TDE
>gi|154302195|ref|XP_001551508.1| hypothetical protein BC1G_09778 [Botryotinia fuckeliana B05.10]
GP---DDDESD---VEAEV------ESD-LGALFSRV--------------EKSGRGVTV
QASTLGSLEALLDFLKV---S----------KIPVANVGIGPVFRRDVMNCGTML--E--
-KQ--KEYAVMLCFDVKIDKEAQQYADDQ--GIKIFTADIIYHLFDSFTKHMQ------V
IAEAKK--EAS
>gi|342880397|gb|EGU81535.1| hypothetical protein FOXB_07951 [Fusarium oxysporum Fo5176]
GP---DDDEDD---IEDEV------ESD-LAVLFNRV--------------EKTGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVLQCGVML--E--
-KA--PDYAIMLCFDVKVDKEAQQYAEDN--GIKIFTADIIYHLFDAFTKHMD------E
QLEKKK--EES
>gi|6319282|ref|NP_009365.1| Fun12p [Saccharomyces cerevisiae S288c]
GP---EDDEDE---LMDDV------MDD-LTGLLDSV--------------DTTGKGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKASTML--E--
-KA--PEYAVMLCFDVKVDKEAEQYAEQE--GIKIFNADVIYHLFDSFTAYQE------K
LLEERR--KDF
>gi|322712454|gb|EFZ04027.1| eukaryotic translation initiation factor 5B [Metarhizium anisopliae ARSEF 23]
GP---DDDEED---IEDEV------VAD-LASLLSRV--------------EKTGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQCGIML--E--
-KA--PDYAVMLCFDVKVDKEAQVYAEEQ--GIKIFTADIIYHLFDSFTKHMD------E
MLEKKK--EES
>gi|367022780|ref|XP_003660675.1| hypothetical protein MYCTH_2299259 [Myceliophthora thermophila ATCC 42464]
GP---DDDESD---LEDEV------ESD-LASLFSRV--------------EKTGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVFKRDVMQCGIML--E--
-KA--PDFAVMLCFDVKIDKEAQAYADEQ--GIKIFTADIIYHLFDSFTKHIK------E
QNEKKK--EES
>gi|302846702|ref|XP_002954887.1| eukaryotic translation initiation factor 5B [Volvox carteri f. nagariensis]
SP---DDDEEE---LKDAV------MED-MADIFSKV--------------DKGGEGVCV
QASTLGSLEALLAFLSS---P--------EVNIPVSGINIGPVHKRDVLRANVMN--E--
-KK-CPKYAVILAFDVPVSKEARDLAEDY--NVKVFTADIIYHLFDQFTAYVK------Q
VKSAEQ--EAA
>gi|258565673|ref|XP_002583581.1| eukaryotic translation initiation factor 5B [Uncinocarpus reesii 1704]
GP---DDDEED---LEDEV------MSD-LENLLSKV--------------SKDNRGVSV
QASTLGSLEALLEFLRV---S----------KIPVANISIGPVYKRDVMRAGTML--E--
-KA--KQFAVMLCFDVKVDKEAQAYADEV--GIKIFTADIIYHLFDDFTKHME------E
ISARKR--EES
>gi|302881941|ref|XP_003039881.1| hypothetical protein NECHADRAFT_64056 [Nectria haematococca mpVI 77-13-4]
GP---DDDEDD---IEDEV------ESD-LAVLFNRV--------------EKSGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQCGIML--E--
-KA--PDYAIMLCFDVKVDKEAQQYAEDQ--GIKIFTADIIYHLFDAFTKHMD------E
QLEKKK--EES
>gi|367045954|ref|XP_003653357.1| hypothetical protein THITE_2115721 [Thielavia terrestris NRRL 8126]
GP---DDDESD---LEDEV------ESD-LASLFSRV--------------EKTGRGVSV
QASTLGSLEALLDFLKE---S----------KIPVANVGIGPVYKRDVMQCGIML--E--
-KA--PDFAVMLCFDVKIDKEAQAYADEQ--GIKIFTADIIYHLFDAFTKHIQ------E
QNEKKK--EES
>gi|372464118|emb|CCF58397.1| hypothetical protein KAFR_0E02440 [Kazachstania africana CBS 2517]
GP---DDDEEE---MMDDV------MDD-ITGLLDSV--------------DTSGKGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKASTML--E--
-RA--PEFAVMLCFDVKVDKEAEQYAEQE--GIKIFNADIIYHLFDSFTAYQQ------Q
LLEQRR--KDF
>gi|380491126|emb|CCF35544.1| hypothetical protein CH063_01330 [Colletotrichum higginsianum]
GP---DDDEDD---IIDEV------ESD-LATLFNRV--------------EKTGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQAGIML--E--
-KA--ADFAVMLCFDVKVDKEAQQYADDV--GVKIFTADIIYHLFDAFTKHMA------E
LLEKKK--EES
>gi|398408009|ref|XP_003855470.1| hypothetical protein MYCGRDRAFT_55505 [Zymoseptoria tritici IPO323]
KD---KDDEDEIEELEEDV------MGD-LENLMSRI--------------AKSGRGVTV
QASTLGSLEALLEFLKV---S----------KIPVANISIGPVHKRDVITASTML--E--
-KA--KEYAVMLCFDVKVDKEAIELAEQM--GVKIFTAEIIYHLFDDFTRHMA------A
LAAQKK--EES
>gi|46110138|ref|XP_382127.1| hypothetical protein FG01951.1 [Gibberella zeae PH-1]
GP---DDDEDD---IEDEV------EAD-LAVLFNRV--------------EKSGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQCGVML--E--
-KA--PDYAIMLCFDVKVDKEAQQYAEDQ--GIKIFTADIIYHLFDSFTKHMD------A
QLEKKK--EES
>gi|387220354|gb|AFJ69849.1| translation initiation factor 5B, partial [Nannochloropsis gaditana CCMP526]
GP---DDDVED---IKEEV------MRD-ITDVMGNL--------------ETDSRGVTV
QASTLGALEALLEYLRK---E-------CKPPVPVARVGIGPIFKKDVTQTGTNI--E--
-KG-LKEFACILAFDVKVDADARAHADEL--GVRIFTAEIIYHLFDQFSNYIK------T
FEEEKK--EKA
>gi|116196470|ref|XP_001224047.1| hypothetical protein CHGG_04833 [Chaetomium globosum CBS 148.51]
GP---DDDESD---LEDEV------ESD-LASLFSRV--------------EKSGRGVSV
QASTLGSLEALLDFLKS---C----------KIPVANVGIGPVFKRDVMQCGTML--E--
-KS--PDFAVMLCFDVKVDKEAQAYADEQ--GIKIFTADIIYHLFDSFTKHIN------E
QNEKKK--EES
>gi|219129822|ref|XP_002185079.1| predicted protein [Phaeodactylum tricornutum CCAP 1055/1]
GP---GDEEED---IKAEV------MSD-LTKLEDKL--------------STDKVGVLV
QASTLGALEALLQFLREETKP----------PIPVSAIGIGRIHKRDVTKISIMN--E--
-KG-HPEFATILAFDVDIEREAREHAEDM--GVRIMTADIIYHLFDQFTRFMD------E
LNQRKR--EEA
>gi|169771199|ref|XP_001820069.1| eukaryotic translation initiation factor 5B [Aspergillus oryzae RIB40]
GP---DDDEED---IEDEV------MSD-LENLLSKV--------------SKDQRGVSV
QASTLGSLEALLEFLRV---S----------KIPVANISIGPVYKRDVMMAGTML--E--
-KA--KEYAVMLCFDVKVDKEAAAYAEEV--GVKIFTADIIYHLFDDFTKHIA------E
LTEKRK--EES
>gi|241949373|ref|XP_002417409.1| eukaryotic translation initiation factor 5B, putative [Candida dubliniensis CD36]
GE---DDDEDD---LMDEV------MDD-LTGLLDSV--------------DTSGKGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKASTML--E--
-RA--PELAVMLCFDVKVDKEAEQYADEQ--NIKIFNADIIYHLFDSFTAYQA------K
LLEARR--KEF
>gi|299472031|emb|CBN80114.1| EIF5B, eukaryotic translation initiation factor 5B [Ectocarpus siliculosus]
GP---DDDEED---IKEEV------MRD-FTDLMK-M--------------DLEPKGVMV
QASTLGALEALMQFLRK---E-------CDPPIPVFAVGIGAVFKKDVMRASIMN--E--
-KG-TPEYATILAFDVKIDSDARRYADEN--GVRIFTADIIYHLFDQFTAHMD------R
LMEQRR--QDA
>gi|255713024|ref|XP_002552794.1| KLTH0D01606p [Lachancea thermotolerans]
GP---EDDEEE---MMDDV------MED-LTGLLDSV--------------DTSGRGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKATAML--D--
-KA--KEFAVMLCFDVKIDKEAEHYAEEQ--GVKIFNADVIYHLFDAFTAYQE------K
LLEQRR--KDF
>gi|367017946|ref|XP_003683471.1| hypothetical protein TDEL_0H04010 [Torulaspora delbrueckii]
GP---DDDEEE---MMDDV------MDD-LTGLLDSV--------------DTSGRGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKAGAML--E--
-KA--PEYAVMLCFDVKVDKEAEQYAEQE--HIKIFNADIIYHLFDAFTAYQE------K
LLEERR--KNF
>gi|254581292|ref|XP_002496631.1| ZYRO0D04554p [Zygosaccharomyces rouxii]
GP---DDDEEE---MMDEV------MDD-LTGLLDSV--------------DTSGRGVTV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKAGAML--E--
-KA--PEYAVMMCFDVKIDKEAEQYAEQE--GIKVFNADVIYHLFDAFTKYQE------D
LLEQRR--KDF
>gi|240278327|gb|EER41834.1| eukaryotic translation initiation factor 5B [Ajellomyces capsulatus H143]
GP---DDDEED---LEDEV------MSD-LESLLSKV--------------SKDNRGVSV
QASTLGSLEALLEFLRV---S----------KIPVANISIGPVYKRDVMRAGTML--E--
-KA--KQFAVMLCFDVKVDKEAQAYAEEA--GIKIFTADIIYHLFDDFTKHME------Q
ITEQKK--EES
>gi|260940701|ref|XP_002614650.1| conserved hypothetical protein [Clavispora lusitaniae ATCC 42720]
GE---DDDEDE---LMEEV------MDD-LTGLLDSV--------------DTSGKGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKATTML--E--
-KA--PELAVMLCFDVKVDKEAEQYAEEQ--KIKIFNADIIYHLFDAFTAYQS------K
LLEVRR--KEF
>gi|367007050|ref|XP_003688255.1| hypothetical protein TPHA_0N00410 [Tetrapisispora phaffii CBS 4417]
GP---DDDEEE---MMDEV------MDD-LTGLLDSV--------------DTSGKGVTV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVFKRDVMKAGTML--E--
-RA--PEFAIMLCFDVKIDREAEDYAEKE--GIKLFNADIIYHLFDAFTAYQE------K
LLEDRR--KNF
>gi|400596370|gb|EJP64144.1| translation initiation factor aIF-2 [Beauveria bassiana ARSEF 2860]
GP---DDDEDD---IEDEV------LSD-LDNLLSRV--------------EKSGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQCGIML--E--
-KA--PDLAIMMCFDVKVDKEAQQYADEQ--GIKIFTADIIYHLFDAFNLHMK------E
MLEKKR--EES
>gi|169620249|ref|XP_001803536.1| hypothetical protein SNOG_13327 [Phaeosphaeria nodorum SN15]
GP---DDDEED---LMDEV------MGD-LAHLLSKV--------------SKTGRGVSV
QASTLGSLEALLEFLRV---S----------KIPVSTISIGPVFRKDVLRAGIML--E--
-KA--KEYAVMLCFDVKVDKEAKAYADEI--GVKIFEADIIYHLFDKFTAHMK------Q
LEEQRK--EES
>gi|302307743|ref|NP_984469.2| ADR373Wp [Ashbya gossypii ATCC 10895]
GP---EDDEED---LMDDV------MDD-LTGLLDSV--------------DKTGKGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKTTTML--E--
-KA--PEFAVMLCFDVKVDKEAEQYAEEQ--GVKIFNADVIYHLFDAFTAYQE------E
LMQKRR--QDF
>gi|323450298|gb|EGB06180.1| hypothetical protein AURANDRAFT_54360 [Aureococcus anophagefferens]
HA---DDDVED---IKEEV------MKD-VSGLVDTL--------------ATEAKGVTV
QASTLGALEALLEFLRN---PGKDRQGKERPPIPVFSATVGPIHKKDVIRAAIMA--Q--
-KG-HDEFACILGFDVPVDPDAQTYADKN--GVKIFTAEIIYHLETHFTTHLD------A
IMEQRR--DDA
>gi|149247269|ref|XP_001528047.1| hypothetical protein LELG_00567 [Lodderomyces elongisporus NRRL YB-4239]
GE---DDDEEE---MMEEV------MDD-LTGLLDSV--------------DTSGKGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKAVTML--D--
-KA--PELAVMLCFDVKVDKEAEHYADEQ--NIKIFNADIIYHLFDAFTAYQN------K
LLEQRR--KEF
>gi|361130988|gb|EHL02718.1| putative Eukaryotic translation initiation factor 5B [Glarea lozoyensis 74030]
GP---DDDESD---IEAEV------ESD-LGALFSRV--------------EKSGRGVTV
QASTLGSLEALLDFLKV---S----------KIPVANVGIGPVFKRDVMNCGTML--E--
-KN--KEYAVMLCFDVKIDKEAQQYADEQ--GIKIFTADIIYHLFDAFTQHMA------V
IAEKKK--EDS
>gi|392576357|gb|EIW69488.1| hypothetical protein TREMEDRAFT_68717 [Tremella mesenterica DSM 1558]
HD---DDEVEV---YKDMA------LED-LSDLSRFI--------------NPKAPGVWV
QASTLGSLEALLEHLKL---S----------KTPVRGFGIGPIYRKDILKAGLML--R--
-RDETAHFAVVLGFDVPVDGDAADYAKKE--GVKIFTDETIYRLGDQYLAYYN------E
VEEAKR--KEA
>gi|401828337|ref|XP_003887882.1| translation initiation factor IF-2 [Encephalitozoon hellem ATCC 50504]
KS-----SEEE---VKNAL------EAD-LESVFSSM--------------ELHQEGVHV
VSSTLGSLEALVSFLKT---S----------NVPISGVSIGTVKKKDMIIVSSMT--K--
-K--HKEYAVILCFDVVLDREIKDMASSM--GVRVFEAKIIYHLLDSYVKFIS------E
EREKNK--KMH
>gi|294655931|ref|XP_458159.2| DEHA2C10956p [Debaryomyces hansenii CBS767]
GE---DDDEEE---IMEEV------MDD-LTGLLDSV--------------DTSGKGVVV
QASTLGSLEALLDFLKD---S----------KIPVMSIGLGPVYKRDIMKASTML--E--
-KA--PEYAVMLCFDVKVDKEAEQYATEQ--NIKIFNADIIYHLFDQFTAYQE------K
LLEARR--KEF
>gi|310792057|gb|EFQ27584.1| translation initiation factor aIF-2 [Glomerella graminicola M1.001]
GP---DDDEDD---IIDEV------ESD-LATLFSRV--------------EKTGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQAGIML--E--
-KA--PDYAIMLCFDVKVDKEAQQYADDV--GVKIFTADIIYHLFDAFTKHMA------E
LLEKKK--EES
>gi|359382236|emb|CCE81073.1| Piso0_003421 [Millerozyma farinosa CBS 7064]
GE---DDDEDE---IMEEV------MDD-LTGLLDSV--------------DTSGRGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKATTML--D--
-KA--PEYAVMLCFDVKVDKEAEQYAMEQ--NIKIFNADIIYHLFDAFTAYQK------E
LLEERR--KAY
>gi|159487705|ref|XP_001701863.1| eukaryotic initiation factor [Chlamydomonas reinhardtii]
QP---EDDEEE---LKDAV------MED-MADIFSKV--------------DKGGEGVCV
QASTLGSLEALLTFLSS---D-------DGGNIPVSGINIGPVHKKDVLRANVMN--E--
-KK-CPKYACILAFDVPVNKEARELAEDY--GVKIFTADIIYHLFDQFTAYVK------Q
IRSAEQ--EAA
>gi|126132054|ref|XP_001382552.1| hypothetical protein PICST_82202 [Scheffersomyces stipitis CBS 6054]
GE---DDDEDE---IMEEV------MDD-LTGLLDSV--------------DTSGKGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKATTML--E--
-KA--PELAVMLCFDVKVDKEAEQYADEQ--NIKIFNADIIYHLFDAFTAYQE------K
LLEIRR--KDF
>gi|406608114|emb|CCH40548.1| Eukaryotic translation initiation factor 5B [Wickerhamomyces ciferrii]
NS---EEEEED---AMDEV------MDD-LTGLLDSV--------------DTSGRGVTV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPIYKRDVMKATTML--D--
-KA--KEYAVMLCFDVKVDKEAQQYADEQ--GIQMFTADVIYHLFDAFTAYQQ------K
LLEQRR--KDF
>gi|50312169|ref|XP_456116.1| hypothetical protein [Kluyveromyces lactis NRRL Y-1140]
GP---DDDEEE---MMDDV------MED-LTGLLDSV--------------DTSGRGVVV
QASTLGSLEALLDFLKD---M----------KIPVMSVGLGPVYKRDIMKACTML--E--
-KA--PELAVMLCFDVKVDKEAEQYAAEQ--HIKIFNADIIYHLFDAFTAYQK------E
LLEKRR--AEF
>gi|320582104|gb|EFW96322.1| eukaryotic translation initiation factor 5B, putative [Ogataea parapolymorpha DL-1]
GE---DDDEDE---LMDEV------MDD-LTGLLDSV--------------DSSGRGVTV
QASTLGSLEALLDFLKD---M----------KIPVMSIGLGPVYKRDVMKAAAML--D--
-KA--KEYAVMLCFDVKIDKEAEQYANEQ--GVTIFNADIIYHLFDSFTAYQQ------K
LLEERR--KEN
>gi|358055875|dbj|GAA98220.1| hypothetical protein E5Q_04903 [Mixia osmundae IAM 14324]
TE---DDDEEE---IKTEI------MTD-LQNLLESV--------------DKTGRGVWV
QASTLGSLEALLEFLKT---S----------KIPVSGINIGPVHRRDAMRASAML--D--
-KA--PEFGVMLCFDVDVDKDAEKLADEV--GLKIFKANIIYHLFDAFTAYNE------A
MLEAKR--KDS
>gi|50542926|ref|XP_499629.1| YALI0A00803p [Yarrowia lipolytica]
GP---DDDEEE---LMDDV------MDD-LTGLLDSV--------------DKSGRGVCV
QASTLGSLEALLDFLKD---M----------KIPVMSIALGPVYKKDVMRATTML--E--
-KD--KSLAIMLCFDVKIDKDAERYADEQ--GVKLFSADIIYHLFDDFVKHQK------K
LQEQKR--LDT
>gi|389628534|ref|XP_003711920.1| eukaryotic translation initiation factor 5B [Magnaporthe oryzae 70-15]
GP---DDDESD---LEEEV------ESD-LAHLFSRV--------------AKSGRGVSV
QASTLGSLEALLDFLKE---C----------KIPVANVGIGPVYKRDVMQCGIML--E--
-KA--PDYAVMLCFDVKVDKEAAQYAEEQ--GIKIFTADIIYHLFDAFTKHQE------E
QLEKKK--EEA
>gi|346970238|gb|EGY13690.1| eukaryotic translation initiation factor 5B [Verticillium dahliae VdLs.17]
GP---DDDEDD---LCDEV------EAD-LAVLFNRV--------------EKTGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQSGIML--E--
-KA--PDYAVMLCFDVKVDKEAQAYAEDV--GVKIFTADIIYHLFDSFTKHMD------E
LLEKKK--EES
>gi|402083997|gb|EJT79015.1| eukaryotic translation initiation factor 5B [Gaeumannomyces graminis var. tritici R3-111a-1]
GP---DDDESD---LEEEV------EGD-LATLFSRV--------------TKTGRGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQCGVML--E--
-KA--PDHAVMLCFDVKVDKEAAAYAEAE--GIKIFTADIIYHLFDAFTKHQA------E
QLEKKR--EEA
>gi|340506857|gb|EGR32916.1| hypothetical protein IMG5_067130 [Ichthyophthirius multifiliis]
NT---HEDEED---AMDLV------MND-LHQVKNKV--------------KLSEQGVGV
AASTLGSLEALLNFLDN---S----------KIPVSYVSVGPVSKDDIMKALKSVLAEEP
ARR-KKEYACMLVFDVKVLPDAQKYAEDN--GVKVFTANIIYHLFDYYTKYQK------E
CIEERK--QEI
>gi|340959962|gb|EGS21143.1| eukaryotic translation initiation factor 5B-like protein [Chaetomium thermophilum var. thermophilum DSM 1495]
GP---DDDEEE---LEEEV------ESD-LQSLFSRV--------------EKTGKGVSV
QASTLGSLEALLDFLKD---C----------KIPVANVGIGPVYKRDVMQCGIML--E--
-KA--PDYAVMLCFDVKVDKEAQQYADEN--GIKIFTADIIYHLFDQFTKHMQ------E
QLEKKK--EES
>gi|71404886|ref|XP_805106.1| translation initiation factor IF-2 [Trypanosoma cruzi strain CL Brener]
HN---GDDKEK---IAHEV------MRE-ANSISDQL--------------SPDGVGVTV
QSSTLGSLEALLAYLKD---M----------KIPVASASIGPLHKRHMIQLLSMK--R--
-K--APRYAVVLAFDVQVSEDARDIAKKN--DIDIFEAKIIYHLFDMFTRYVA------E
YENREK--ERA
>gi|281205776|gb|EFA79965.1| eukaryotic translation initiation factor 5B [Polysphondylium pallidum PN500]
GE---DDDLEE---LKREA------QKD-VDSVLATD--------------DTEEIGVTI
QASTLGSLEAFSTFLKG---E----------KIPVAFKAIGPVHKKHVMNAAIMA--N--
-K--DPKYAILLAFGVKVEESAMQTANEL--KITIMSEETIYLFVDRLKTYFG------A
IKEKLR--EQT
>gi|66815935|ref|XP_641984.1| eukaryotic translation initiation factor 5B [Dictyostelium discoideum AX4]
GP---NDDIEK---IRAEA------KRE-VDSVLNDV--------------ETSGIGVSV
QASTLGSLEAFLNFLKK---I----------KIPVANVAIGPVHKKHIMNASIML--D--
-K--DPKYAILLAFDVKIEESAIQAANEM--KVQVLSDETIYLFEEKLKKHFG------A
IKEKLR--AET
>gi|84043628|ref|XP_951604.1| translation initiation factor IF-2 [Trypanosoma brucei TREU927]
RP---GDDKEA---VAKEV------MKD-ANSITDQL--------------SPDGVGVTV
QSSTLGSLEALLSFLNK---M----------KIPVASASIGPLHKRHMINVLSMK--R--
-K--SPRHAVVLAFDVEISDDARDIAKKN--DIDMFEAKIIYHLFDMFTRYIN------E
YEKREK--DKA
>gi|157875274|ref|XP_001686037.1| putative translation initiation factor IF-2 [Leishmania major strain Friedlin]
HA---NDNKEK---IAELV------MKD-ATNINEFL--------------DPDGLGVSV
QSSTLGALEALLSFLKG---M----------KIPVASIAIGPIYKRHMHQVLSMK--R--
-R--EPRYAVILAFDVPVSEEAREIAKKN--DIDIFEANIIYHLFDKFTRYIN------E
YEQREK--DRL
>gi|261326507|emb|CBH09468.1| translation initiation factor IF-2, putative [Trypanosoma brucei gambiense DAL972]
RP---GDDKEA---VAKEV------MKD-ANSITDQL--------------SPDGVGVTV
QSSTLGSLEALLSFLNK---M----------KIPVASASIGPLHKRHMINVLSMK--R--
-K--SPRHAVVLAFDVEISDDARDIAKKN--DIDMFEAKIIYHLFDMFTRYIN------E
YEKREK--DKA
>gi|354683905|gb|AER35081.1| eukaryotic translation initiation factor 5B [Dictyostelium lacteum]
DE---DDDINA---IKAEA------IKE-VESVLNDI--------------ETSGIGVSI
QASTIGSLEAFSSFLKK---I----------KIPVANVAVGPVAKKHVMSAAIML--E--
-K--DPKYAILLAFDVKIEDSAKQAANDM--KVKILSEETIYLFEKKLKDHFD------E
IRQKLR--EET
>gi|355336770|gb|AER57870.1| eukaryotic translation initiation factor 5B [Acytostelium subglobosum]
ED---DDDLER---LKDDA------QRE-VDSVLQDV--------------VTTGVGVSV
QASTLGSLEAFLAFLKK---I----------NVPVASVAIGPVHKKNIMDAAIMV--E--
-K--DPKYAILLAFDVKIEESAQQAAHDM--KITIMSEETIYLFEKRLDDHFG------A
IKERLR--TET
>gi|300708693|ref|XP_002996521.1| hypothetical protein NCER_100390 [Nosema ceranae BRL01]
NN-----NEEE---VKLKL------DKD-YQSVISSI--------------KLDESGVHV
VASTLGSLEALLSFLKK---S----------EIKVSAVSIGSIKKKDLLIIASNQ--E--
-K--NNEYGAVLCFDVIVDKDIKDLAHNL--HIKIFEAKIIYHLFDQYTNYIN------N
MKSKAK--EIH
>gi|328867012|gb|EGG15395.1| eukaryotic translation initiation factor 5B [Dictyostelium fasciculatum]
TE---DDDLED---LKAQA------QSE-IDSVLNDV--------------ETSGVGVSV
QASTLGSLEAFISFLKK---I----------KVPVANVAIGPIHKKNVMACSIMR--E--
-K--DPKYAIMLAFDVKIEESAQQAANDM--KITIMSEDTIYLFEKRLEDHFN------A
IKEKLR--DET
>gi|340052398|emb|CCC46676.1| putative translation initiation factor IF-2 [Trypanosoma vivax Y486]
RD---GDDRES---IVAEV------MKD-ANSIADHL--------------SPDGVGVTV
QSSTLGSLEALLAFLRD---M----------KVPVASAAIGPLYKRHMIQVLSTK--R--
-K--NPRYGIVLAFDVTVSDDAREIAAKN--EIDIFEAKIIYHLFDQFTRHTA------E
YERLEK--ERA
>gi|218186906|gb|EEC69333.1| hypothetical protein OsI_38435 [Oryza sativa Indica Group]
KP---GDELGQ---SEAKNQRNENEEGN-VIQEISRL--------------KTCKEGVYV
QASTFGILEAIIEHLNS---P--------GVNVPVSGCNLGPIEKKDVMKASAML--K--
-R--KEEYAAILAFNVRVMPEADVLASES--GVKIVTADTLYKLVDSFNEHIK------R
SKELKK--MQC
>gi|118390081|ref|XP_001028031.1| Elongation factor Tu GTP binding domain containing protein [Tetrahymena thermophila]
NT---NDEEQT---AIDLV------MSD-YNQVKKKV--------------KLVNIGVGV
AASTLGSLEALLDFLEK---K----------KIPVSYVSVGPVSKDSITKALKSVLADDP
KKR-KQEYACMLVFDVKILPDAQKYAEEN--GVKILTANIIYHLQDQYVKYVQ------E
CEEERK--KEE
>gi|154417092|ref|XP_001581567.1| Elongation factor Tu GTP binding domain containing protein [Trichomonas vaginalis G3]
HS---DEDVEI---LKKRV------EAD-ITAITSSV--------------NKNEDGLLV
QASTLGSLEALLSYLKS---Q----------NVNVAAVGIGPLYKKDIQQILHIA--Q--
-A--NPKYACVLCFNVEISADAKTFAQQN--DIKIFSAEIIYHLTDMYAKYIE------D
LKVKAR--EAA
>gi|145507842|ref|XP_001439876.1| hypothetical protein [Paramecium tetraurelia strain d4-2]
NS---QEDIDR---ATEII------NNE-MEEVKKYI--------------KLQNQGVGV
AASTLGSLEALLQYLNS---Q----------DIPVSYVSVGPVSKDDVMKALKNVLLEDV
NRR-KKEYACMLVFDVKILPDAQKFAEEN--QIKIFEANIIYHLFTKFTEFIK------Q
VKEERK--KKE
>gi|53793462|dbj|BAD53222.1| translation initiation factor if-2-like [Oryza sativa Japonica Group]
-P---GDDQEK---SVNKA------MAE-MVVLMNRI--------------DKNS-----
---------------------------------------DGPVHRKDVMKASVML--E--
-K--KKEYAAIFAFDVKVMPDAREIANES--GVKIFVADVIYHLFDQFTTYIE------G
LREIEK--DEK
>gi|387593075|gb|EIJ88099.1| eukaryotic translation initiation factor 5B [Nematocida parisii ERTm3]
KN---DSDTDR---IIEEA------DEQ-IRETIQAFISGDKQTTSGTIFDVVGEDGIHA
QASTLGALEALISILKK---A----------NIPIRTVGVGNISKKDVIKVSTIS--E--
-R--HPEYSVMLCFDVAPSQEMQALGKEM--KVKFLTAEIIYHLTEKYKKHME------E
QWALAE--EQL
>gi|159108893|ref|XP_001704714.1| Translation initiation factor IF-2, putative [Giardia lamblia ATCC 50803]
DP---GDNLED---LKECV------MAD-IHDMAKQF--------------KFSNVGIYL
NASSLGSMEALITYLSS---E--------KTKVPLAGCAIGPISKNTIQEAALQL--E--
-RT-NPEYACILAFDIEVDKATEDYAKIN--KVKIFRADIIYHLYDMFVEHLK------Q
YKLERR--EAL
>gi|340502028|gb|EGR28748.1| hypothetical protein IMG5_169450 [Ichthyophthirius multifiliis]
NC---QEDEDY---AMTML------KDN-H-LELKKI--------------QLQEQGVVV
LASSLGSLEALCEFLQS---Q----------KIPISYTSVGSVCKECVSIALKQGI----
-VG-QKEFACILAFDVKVLPDAAKYAEEN--HIKVFTAKIIYQLFDSFKKYQE------E
CILIRK--KEE
>gi|294891639|ref|XP_002773664.1| eukaryotic translation initiation factor 5B, putative [Perkinsus marinus ATCC 50983]
A----------------------------PNTVTSPM--------------AGSGNGITM
KCSSMGGVEALTKLVKE---V---------VRAPIGLAAIGDVHLLDVRKTSCVL--A--
-N--RGKYGIILAYDVKVNHDARAEAEKL--GVRIIENDVIYKLIEELKTYLQ------G
KEEDRR--KEE
>gi|218188538|gb|EEC70965.1| hypothetical protein OsI_02584 [Oryza sativa Indica Group]
-L---GDDQEK---SVNKA------MAE-MVVLMNRI--------------DKNS-----
---------------------------------------DGV-YVKDVMKASVML--E--
-K--KKEYASIFAFDVKVMPDAREIANES--SVKIFVADVIYHLFDQFTTYIE------G
LREIEK--DEK
